### ISSUE TITLE
Hola incidencias... necesito ayuda !!!

### ISSUE THREAD

**Issue by wlbinet1** [maestria-geotel-201902/unidad-0-asignacion-1-asig-conrstudio-issues-wlbinet1#1]
***Estimado profesor José Ramón,***
A lo primero, cuando indicabas que vaya a mi **repo** estuve un poco perdida.
Pero ya le encontré el truco /secuencia para crear un cuestionamiento al grupo o enviar un mensaje/comentario al responsable del repositorio raiz.
## *Lo que debo es aperturar la mente a un flujo diferente de trabajo*
# **Me esta gustando !!!**

**Comment by geofis** [comment]
Je je, esto será poco a poco, pero sin duda habrá momentos en los que habrá que abrir mucho las mentes, tal como comentas.
